#!/usr/bin/env bash
# ============================================================================
#  setup.sh — writes Config/Secrets.swift and generates the Xcode project.
# ============================================================================
#  Run:  ./setup.sh
#
#  App identity, branding and feature flags are NOT here — they live in the
#  code (Config/AppConfig.swift, Core/Theme/DesignSystem.swift, project.yml),
#  so this script never rewrites tracked files and never collides with a pull.
#
#  Only needed when your API keys change. To build without keys, run
#  `xcodegen generate` — the app falls back to a local purchase stub and
#  no-op analytics.
# ============================================================================

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"
SECRETS="$PROJECT_ROOT/Config/Secrets.swift"

if [ -t 1 ]; then
    GREEN='\033[0;32m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'
    BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'
else
    GREEN='' YELLOW='' CYAN='' BOLD='' DIM='' RESET=''
fi

printf "${BOLD}${CYAN}\n  Find My Headphones — key setup${RESET}\n\n"
printf "${DIM}  Press Enter to leave a key blank.\n"
printf "  Blank RevenueCat key = local purchase stub (debug builds only).\n"
printf "  Blank TelemetryDeck id = analytics disabled.${RESET}\n\n"

# Keep existing values as the defaults so re-running doesn't wipe them.
existing_value() {
    [ -f "$SECRETS" ] || return 0
    LC_ALL=C sed -n "s/.*let $1: String = \"\([^\"]*\)\".*/\1/p" "$SECRETS" | head -1
}

DEFAULT_RC="$(existing_value revenueCatAPIKey)"
DEFAULT_TD="$(existing_value telemetryDeckAppID)"

prompt() { # prompt <var> <label> <default>
    local _label="$2" _default="$3" _value=""
    if [ -n "$_default" ]; then
        printf "  ${YELLOW}${BOLD}%s${RESET} ${DIM}[%s]${RESET}: " "$_label" "$_default"
    else
        printf "  ${YELLOW}${BOLD}%s${RESET}: " "$_label"
    fi
    read -r _value
    [ -z "$_value" ] && _value="$_default"
    eval "$1=\"\$_value\""
}

prompt REVENUECAT_KEY "RevenueCat API key"   "$DEFAULT_RC"
prompt TELEMETRY_ID   "TelemetryDeck app ID" "$DEFAULT_TD"

cat > "$SECRETS" <<SECRETS_EOF
//
//  Secrets.swift
//  Generated by setup.sh — gitignored, do NOT commit.
//

import Foundation

public enum Secrets {
    public static let telemetryDeckAppID: String = "${TELEMETRY_ID}"
    public static let revenueCatAPIKey: String = "${REVENUECAT_KEY}"
}
SECRETS_EOF

printf "\n${GREEN}  Wrote Config/Secrets.swift${RESET}\n"

if command -v xcodegen &> /dev/null; then
    cd "$PROJECT_ROOT"
    xcodegen generate --quiet 2>/dev/null || xcodegen generate
    printf "${GREEN}  Regenerated FindMyHeadphones.xcodeproj${RESET}\n\n"
    printf "  Open it with: ${BOLD}open FindMyHeadphones.xcodeproj${RESET}\n\n"
else
    printf "${YELLOW}  xcodegen not found — install with: brew install xcodegen${RESET}\n"
    printf "${YELLOW}  Then run: xcodegen generate${RESET}\n\n"
fi
