//
//  AppConfig.swift
//  __APP_NAME__
//
//  Generated by TheSwiftKit
//

import Foundation
import SwiftUI

public enum BackendProvider: String, Codable, CaseIterable, Sendable {
    case supabase
    case local
}

public enum LayoutStyle: String, Codable, CaseIterable, Sendable {
    case list
    case grid
}

public struct Branding: Codable, Sendable {
    public var primaryColorHex: String
    public var accentColorHex: String
    public init(primaryColorHex: String, accentColorHex: String) {
        self.primaryColorHex = primaryColorHex
        self.accentColorHex = accentColorHex
    }
}

public struct LegalLinks: Codable, Sendable {
    public var privacyPolicyURL: URL
    public var termsURL: URL
}

public struct AppConfig: Codable, Sendable {
    public var appName: String
    public var bundleId: String
    public var backend: BackendProvider
    public var layout: LayoutStyle
    public var onboardingStyle: OnboardingStyle
    public var branding: Branding
    public var featureFlags: FeatureFlags
    public var legal: LegalLinks

    public init(
        appName: String,
        bundleId: String,
        backend: BackendProvider,
        layout: LayoutStyle,
        onboardingStyle: OnboardingStyle,
        branding: Branding,
        featureFlags: FeatureFlags,
        legal: LegalLinks
    ) {
        self.appName = appName
        self.bundleId = bundleId
        self.backend = backend
        self.layout = layout
        self.onboardingStyle = onboardingStyle
        self.branding = branding
        self.featureFlags = featureFlags
        self.legal = legal
    }
}

public extension AppConfig {
    // Default config populated by generator; safe local defaults provided.
    static var `default`: AppConfig {
        AppConfig(
            appName: "__APP_NAME__",
            bundleId: "__BUNDLE_ID__",
            backend: .supabase,
            layout: .list,
            onboardingStyle: .carousel,
            branding: Branding(
                primaryColorHex: "__PRIMARY_COLOR__",
                accentColorHex: "__ACCENT_COLOR__"
            ),
            featureFlags: FeatureFlags(auth: true, appleSignIn: true, charts: true, reviewPrompt: true, inAppFeedback: true, biometricLock: true, localization: true, paywallTemplates: true, widgets: true, questionnaireOnboarding: true, gamification: true, aiPro: true, camera: true, reminders: true, swiftDataStore: true),
            legal: LegalLinks(
                privacyPolicyURL: URL(string: "__PRIVACY_URL__") ?? URL(string: "https://example.com/privacy")!,
                termsURL: URL(string: "__TERMS_URL__") ?? URL(string: "https://example.com/terms")!
            )
        )
    }
}
